name: Validate

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  unit-tests:
    runs-on: "ubuntu-latest"
    name: Unit tests
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4"

      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.12"

      - name: "Run unit tests"
        run: "python -m unittest discover -s tests -v"

  hassfest:
    runs-on: "ubuntu-latest"
    name: Check with hassfest
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4"

      - name: "Run hassfest"
        uses: "home-assistant/actions/hassfest@master"

  hacs:
    runs-on: "ubuntu-latest"
    name: Check with HACS Action
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4"

      - name: "Run HACS Action"
        uses: "hacs/action@main"
        with:
          category: "integration"
